### ISSUE TITLE
Can't use the Python module name client

### ISSUE THREAD

**Issue by JoyceXinyueWang** [data61/anonlink-client#14]

**Comment by hardbyte** [comment]
We are assuming end users will install this Python package (instead of directly installing clkhash), currently it would be installed as `client` which is very generic and could clash with other Python modules or packages named `client`. Instead the pypi package could be the same as the github repo: `anonlink-client`, and the Python package could be `anonlinkclient`.

Perhaps `anonlink.client` is possible too? That would be the cleanest solution.
